### ISSUE TITLE
Documentation README /src

### ISSUE THREAD

**Issue by Naomivanes** [naturalis/barcode-constrained-phylogeny#39]
Explain each rule from snakefile_phylogeny in readme

**Comment by rvosa** [comment]
A nice way to do this would be to include the graphviz figure in the readme. How was that created? I notice the figure is now in a non-standard folder. Would be great if it sat in doc/.

**Comment by Naomivanes** [comment]
Made it using commmand snakemake --snakefile snakefile_phylogeny -R all  --dag
 and visualize the output using Graphviz online. I'll add it to doc/.

**Comment by rvosa** [comment]
Done: https://github.com/naturalis/barcode-constrained-phylogeny/commit/6c8bdc8e933851d0c5447d1f9972fcf7b3f23506
