### ISSUE TITLE
Release generated files using Zenodo 

### ISSUE THREAD

**Issue by Naomivanes** [naturalis/barcode-constrained-phylogeny#40]
- [x] Barcode database
- [x] Opentol database (megatree loader output)
- [x]  FASTA files
- [x] Alignments
- [x] Constraint trees
- [x] Subtrees
- [x] Supertree

**Comment by rvosa** [comment]
These are all in the `results/` folder. I have now released the zipped contents of this folder as produced by the pipeline v1.0.0 (tagged release) on Zenodo as [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.10519081.svg)](https://doi.org/10.5281/zenodo.10519081)
