### ISSUE TITLE
Barcode database has no indexes or primary keys

### ISSUE THREAD

**Issue by rvosa** [naturalis/barcode-constrained-phylogeny#48]
The file BOLD_COI-5P_barcodes.db has no indexes. For example, the column barcode.taxon_id should be indexed so that joins with taxon.taxon_id go MUCH faster. Also, taxon.taxon_id seems like it should be a primary key but it is not unique.

**Comment by Naomivanes** [comment]
I have some old DB's after each step so I can see it happens after map_to_opentol. I do not know why yet but a quickfix is to drop duplicate rows in the alter_db function if you need it now.

**Comment by rvosa** [comment]
How are we generating taxon.taxon_id? The name suggests that it is a primary key, which means that this needs to be specified when the table is created. Also, once we're entering records in the taxon table we should let SQLite generate the primary key values automatically. If we try to do this manually with some sort of counter then that might cause problems.

**Comment by rvosa** [comment]
I think I understand what is going on: inside `map_opentol.py` a temporary table is [generated on the fly](https://github.com/naturalis/barcode-constrained-phylogeny/blob/2748916650da08dab497fa7b2543743e42af475d/src/map_opentol.py#L139) that is then [renamed](https://github.com/naturalis/barcode-constrained-phylogeny/blob/2748916650da08dab497fa7b2543743e42af475d/src/map_opentol.py#L156) to the taxon table. The temporary table does not have a primary key so renaming it results in the keyless table. What needs to happen is that the temp table is created separately first and then the data are appended to it. I don't understand the control flow in the script well enough to do this, so please have a look at it.
