### ISSUE TITLE
Change alignment method

### ISSUE THREAD

**Issue by Naomivanes** [naturalis/barcode-constrained-phylogeny#52]
Use HMMer to align sequences to a COI-5P model with pairwise alignment for scalability. With the output of HMMer the sequences can be checked if its forward or reverse.
 
1.	Get refs.hmm from zip file https://github.com/psomervuo/FinPROTAX  and save it in repo 
2.	HMM align using profile and fasta file
3.	Use stockholm file to check which one of the is the forward sequence (most * in alignment)

**Comment by Naomivanes** [comment]
@rvosa do we need to make own profile for matk and rbcl using HMMer build?

**Comment by rvosa** [comment]
Yes we do! We probably need them individually, one each for the full barcode markers. Maybe check first if somebody already made these.

**Comment by rvosa** [comment]
Making an alignment with `hmmalign` and getting the score. Do this for both 5' and 3' orientations. Get the one with the most `*` and store the aligned sequence.

```{python}
from Bio.AlignIO import read as read_alignment
from subprocess import run
run(['hmmalign', '-o', outfile, hmmfile, seqfile])
alignment = read_alignment(outfile, "stockholm")
alignment.column_annotations['posterior_probability'] # count '*'
```
