### ISSUE TITLE
OPTION: Integrate perl tool db into custom db 

### ISSUE THREAD

**Issue by Naomivanes** [naturalis/barcode-constrained-phylogeny#54]
Feedback Rutger: The database from perl-bio-phylo-forest-dbtree (rule megatree-loader) could be integrated into our own custom db (both use Opentol ID's).

**Comment by rvosa** [comment]
Expanding on this for future reference:
- the `megatree-loader` creates a sqlite3 database that consists of a single table whose schema and semantics are explained here: https://doi.org/10.1111/2041%2D210X.13337
- when applied to the opentree newick file whose tip labels are Opentol IDs, the database that `megatree-loader` produces will contain these in the `name` column
- hence, if this table is merged into the database that our pipeline produces, the values of the `name` column match the Opentol IDs that we use elsewhere. 
- the logical thing to do is to index the `name` column and have other tables refer to it by way of a foreign key constraint
