### ISSUE TITLE
Create v1.1.0

### ISSUE THREAD

**Issue by rvosa** [naturalis/barcode-constrained-phylogeny#84]

**Comment by rvosa** [comment]
https://github.com/naturalis/barcode-constrained-phylogeny/releases/tag/v1.1.0

**Comment by rvosa** [comment]
Hi @zahrag, I'm not actually tagging you to assign anything. This is just to let you know that there's the tagged v1.1.0 now in existence. I propose you branch from that while I rework some of the database import logic.

**Comment by zahrag** [comment]
@rvosa Thank you for clarifying this. Sure, will follow as you mentioned.
