### ISSUE TITLE
makeblastdb.sh shell script not portable

### ISSUE THREAD

**Issue by JWesseling** [naturalis/barcode-constrained-phylogeny#86]
In snakemake step rule: makeblastdb 

Gives this error in the log:
workflow/scripts/makeblastdb.sh: 14: [[: not found
BLAST options error: File results/blast/blastdb.fa is empty

Additionally on first run the directory results/fasta/family is not present and needs to be created before running in order for the pipeline to work.

**Comment by rvosa** [comment]
This is due to the shell script not being portable. Can you correct this so that it uses standard shell commands that are portable between shells?

**Comment by rvosa** [comment]
But what about the error for line 14?

**Comment by JWesseling** [comment]
That took some more digging but I got it fixed by changing `[[ ${i} == 1 ]]` to `[ "${i}" = 1 ]`  the previously mentioned change to look for ott followed by digits was still necessary to run the program.

Could you check if it still runs when written like this on your shell? Or should I just put the changed version in the repository?

**Comment by rvosa** [comment]
Please commit it, I'll test it on my end. Thanks!

**Comment by rvosa** [comment]
Tested. Works 👍
