### ISSUE TITLE
Incongruencies in main README

### ISSUE THREAD

**Issue by JWesseling** [naturalis/barcode-constrained-phylogeny#87]
Multiple statements missing or incorrect in the main README:

- The version of the BOLD database in readme differs from the version in config.yml
- It is not stated that the Open Tree of Life database should be downloaded and stored in resources

**Comment by rvosa** [comment]
The aim is that the pipeline is compatible with the most recent releases. Can you update the documentation to reflect this?

**Comment by JWesseling** [comment]
I updated the documentation
