### ISSUE TITLE
DNA barcode sequence field in BOLD tsv

### ISSUE THREAD

**Issue by zahrag** [naturalis/barcode-constrained-phylogeny#89]
Using the latest BOLD tsv released on April 5th 2024, the field indicating DNA nucleotide barcode sequence is nucraw.
This is not compatible with the code.

**Comment by rvosa** [comment]
Is it possible that this is the same issue as #88, which @AnnemiekeSchonthaler has been working on?

**Comment by AnnemiekeSchonthaler** [comment]
Edited the code so it can take both nuc and nucraw as column names now

**Comment by rvosa** [comment]
Is this throughout the code base? It looks like `nucraw` is still being referenced in various locations: https://github.com/search?q=repo%3Anaturalis%2Fbarcode-constrained-phylogeny%20nucraw&type=code

**Comment by rvosa** [comment]
Replaced in all occurrences.
