### ISSUE TITLE
results/fasta/family folder missing

### ISSUE THREAD

**Issue by zahrag** [naturalis/barcode-constrained-phylogeny#90]
Running the code every time demands results/fasta/family directory being existed, however somehow the directory is removed if the code compilation fails and so each time it is required ti manually create the directory.
It would be easier if the code creates the directory automatically itself.

**Comment by rvosa** [comment]
Done in the odonata dev branch. https://github.com/naturalis/barcode-constrained-phylogeny/commit/c675e80705bbe964bdac624fb776c5c3b7875315
